const { Router } = require('express');
const rutas = Router();
rutas.use('/pedidosllevar', require('./rutasPedidosLlevar'));
rutas.use('/pedidosdetallepedido', require('./rutasDetallePedido'));
rutas.use('/pedidos', require('./rutasPedidos'));
rutas.use('/pedidoscancelados', require('./rutasPedidosCancelados'));
rutas.use('/pedidoselaborados', require('./rutaspedidoselaborados'));
rutas.use('/pedidosmesa', require('./rutasPedidosMesa'));
rutas.use('/pedidosyventas', require('./rutasPedidosyVentas'));
module.exports = rutas;